// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

// Test for manual visual verification of rotation
//
// The green rectangle should be 45 degree rotated inside the black rectangle
//
// The rectangle with the linear gradient should be rotated by 315 degrees
// inside the other black rectangle

TestCase := Window {
    width: 800px;
    height: 600px;

Rectangle {
            x: 50px;
            y: 50px;
            width: 50px;
            height: 50px;
            border-width: 1px;
            border-color: black;
            
        }

  Rectangle {
            x: 50px;
            y: 50px;
            width: 50px;
            height: 50px;
            border-width: 1px;
            border-color: black;
            rotation-angle: 45deg;
            rotation-origin-x: 0;
            rotation-origin-y: 0;
            background: area1.has-hover? green : red;
            
            Rectangle {
                x: area1.mouse-x;
                y: area1.mouse-y;
                width: 5px;
            height: 5px;
            background: maroon;
            }
            
            area1:= TouchArea {
                        
                    }
        }
}
