# Copyright © SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

[package]
name = "i-slint-common"
description = "Helper crate for sharing code & data structures between i-slint-core and slint-compiler"
authors.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
path = "lib.rs"

[features]
default = []
shared-fontique = ["dep:fontique", "dep:ttf-parser"]

[dependencies]
ttf-parser = { workspace = true, optional = true }
fontique = { version = "0.5.0", optional = true }

[target.'cfg(not(any(target_family = "windows", target_vendor = "apple", target_arch = "wasm32", target_os = "android")))'.dependencies]
libloading = { version = "0.8.0", optional = true }

[package.metadata.docs.rs]
rustdoc-args = ["--generate-link-to-definition"]
