// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

export component TestCase inherits Window {
    width: 64px;
    height: 64px;
    VerticalLayout {
        Text {
            text: "Hello _Everyone_ how is it **going**. You can ~~not~~ continue";
            wrap: word-wrap;
            color: green;
            font-size: 10px;
            is_markdown: true;
        }
    }
}
