// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

export component TestCase inherits Window {
        MarkdownText {
        x: 100px;
        y: 100px;
            text: "<u>Underlines</u> ~~strikethrough~~\n[**link in bold**](google.com)";
            wrap: word-wrap;
            color: green;
            font-size: 10px;
        }
}
